# Schema for the configuration files of the WeeShop Molla theme.
weeshop_adminimal.settings:
  type: theme_settings
  label: 'weeshop_adminimal settings'
  mapping:
    custom_css:
      type: boolean
      label: 'Custom css'
    disable_google_fonts:
      type: boolean
      label: 'Disable google fonts'
